// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs folder structure. Ordering and
 * category labels are driven by:
 *   - `sidebar_position` front matter on each doc, and
 *   - a `_category_.json` file inside each section directory.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
